# Generated by Django 2.2.2 on 2022-05-27 14:22

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='工单类型')),
                ('ticket_title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='工单名称')),
                ('desc', models.TextField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('is_auto', models.IntegerField(blank=True, choices=[(0, '是'), (1, '否')], default=0, null=True, verbose_name='是否可自动化')),
                ('helper', models.TextField(blank=True, max_length=4096, null=True, verbose_name='帮助信息')),
                ('extra_params', jsonfield.fields.JSONField(blank=True, max_length=4096, null=True, verbose_name='扩展字段')),
                ('handle_user', models.ManyToManyField(to='auth.Group', verbose_name='选择处理人')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='工单名称')),
                ('app_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='APPCODE')),
                ('active_type', models.IntegerField(blank=True, choices=[(0, '等待处理'), (1, '进行中'), (2, '完成'), (3, '驳回')], default=0, null=True, verbose_name='状态')),
                ('qa_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='QA')),
                ('op_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='OPS')),
                ('create_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='创建人')),
                ('extra_params', jsonfield.fields.JSONField(blank=True, max_length=4096, null=True, verbose_name='工单详情')),
                ('detail', models.TextField(blank=True, max_length=4096, null=True, verbose_name='工单详情')),
                ('handle_result', models.TextField(blank=True, max_length=4096, null=True, verbose_name='处理意见')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ticket.TicketType', verbose_name='工单类型')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'ticket',
            },
        ),
    ]
