# Generated by Django 2.2.2 on 2022-05-29 03:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_auto',
            field=models.IntegerField(default=1, verbose_name='是否可自动化'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='extra_params',
            field=jsonfield.fields.JSONField(blank=True, max_length=4096, null=True, verbose_name='扩展表'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='is_auto',
            field=models.IntegerField(choices=[(0, '是'), (1, '否')], default=1, verbose_name='是否可自动化'),
        ),
    ]
