# Generated by Django 2.2.2 on 2022-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0002_auto_20220529_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_consuming',
            field=models.IntegerField(blank=True, null=True, verbose_name='工单耗时'),
        ),
    ]
